# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - ::1
    - 127.0.0.1

logger:
  default: debug
  logs:
    custom_components.huawei_solar: debug
    huawei_solar: debug
    pymodbus: debug # only include this if you're having connectivity issues
